import { requireNativeModule } from 'expo-modules-core';

export interface ResolvedBookmark {
  uri: string;
  // True when iOS decides the bookmark is stale and should be regenerated by the
  // caller (e.g. the underlying file was moved). The URI is still usable; the
  // caller should re-create the bookmark from it to keep future resolves cheap.
  isStale: boolean;
}

export interface FileBookmarkModuleType {
  // Encodes a file URL into a Security-Scoped Bookmark (base64 string) so the
  // app can re-open the file across launches. Returns null when the URL can't
  // be resolved or the system denies bookmark creation.
  createBookmark(uri: string): Promise<string | null>;

  // Resolves a previously-created bookmark back into a usable URI, starting
  // security-scoped access. Returns null when the bookmark can't be resolved
  // (file deleted, container removed, etc.). Access is held for the rest of
  // the app's lifetime — iOS reclaims it at termination.
  resolveBookmark(base64: string): Promise<ResolvedBookmark | null>;

  // Reads a file's UTF-8 text via an NSFileCoordinator coordinated read, which
  // makes the provider materialize (download) a not-yet-downloaded File Provider
  // placeholder (e.g. Google Drive) before reading. expo-file-system's
  // File.text() does an uncoordinated read that throws "no such file" or hangs
  // on such placeholders. Rejects when the file can't be read.
  readFileCoordinated(uri: string): Promise<string>;

  // Returns the human-readable display name of the File Provider that hosts
  // this file (e.g. "Google Drive", "Dropbox") via iOS's NSFileProviderManager.
  // Returns null when the URI is not hosted by a third-party File Provider —
  // the caller should fall back to URI-based classification in that case.
  getProviderDisplayName(uri: string): Promise<string | null>;
}

const FileBookmarkModule = requireNativeModule<FileBookmarkModuleType>('FileBookmark');

export default FileBookmarkModule;
