import { requireNativeModule } from 'expo-modules-core';

export interface ResolvedBookmark {
  uri: string;
  // True when iOS decides the bookmark is stale and should be regenerated by the
  // caller (e.g. the underlying file was moved). The URI is still usable; the
  // caller should re-create the bookmark from it to keep future resolves cheap.
  isStale: boolean;
}

export interface FileBookmarkModuleType {
  // Encodes a file URL into a Security-Scoped Bookmark (base64 string) so the
  // app can re-open the file across launches. Returns null when the URL can't
  // be resolved or the system denies bookmark creation.
  createBookmark(uri: string): Promise<string | null>;

  // Resolves a previously-created bookmark back into a usable URI, starting
  // security-scoped access. Returns null when the bookmark can't be resolved
  // (file deleted, container removed, etc.). Access is held for the rest of
  // the app's lifetime — iOS reclaims it at termination.
  resolveBookmark(base64: string): Promise<ResolvedBookmark | null>;
}

const FileBookmarkModule = requireNativeModule<FileBookmarkModuleType>('FileBookmark');

export default FileBookmarkModule;
